config/routes.rb
Rails.application.routes.draw do
  # get "posts/index" => "posts#index"
  get 'new' => 'home#new'
  post 'judge' => 'home#judge'
end
  Rails.application.routes.draw do
    mount API::Root => '/'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    flash.now[:notice] = "Found the about page!" if request.path == '/pages/about'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def new
    @card_form = CardForm.new
  end



  def judge
    hands = params[:card_form][:hands]
    @card_form = CardForm.new(hands)

    if @card_form.valid?
      flash[:hands] = @card_form.judge
    else
      flash[:hands] = @card_form.error_messages
    end
    redirect_to new_url
  end
end

app/controllers/posts_controller.rb
# いらないっぽい
# class PostsController < ApplicationController
#   def index
#
#   end
# end
#

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/new.html.erb
<header>
  <div class="header-logo">

  </div>
  <ul class="header-menus">
    <li></li>
  </ul>
</header>

<head>
</head>
<body>
  <h1>・</h1>
  <p>・</p>
  <%#= image_tag 'top_background' %>
  <div class="form">
    <div class="form-body">
      <%= form_for @card_form, url: judge_url do |f| %>
        <%= f.text_field :hands %>
        <%= f.submit '判定' %>
      <% end %>
      <%= flash[:hands] %>
    </div>
  </div>
</body>




<!--    <textarea></textarea>-->
<!--    <input type="submit" value="Check">-->
<!--    #{name}結果表示したい-->
<!--  </div>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Porker Judge</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/posts/index.html.erb
<!-- <div class="jumbotron">-->
<!--  <h1 class="display-2">Welcome</h1>-->
<!--<div class="main posts-new">-->
<!--  <div class="container">-->
<!--    <h1 class="form-heading">投稿する</h1>-->
<!--    <!-- プロゲートコピーここから -->-->
<!--    <div class="form">-->
<!--      <div class="form-body">-->
<!--        <textarea></textarea>-->
<!--        <input type="submit" value="投稿">-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->
<!--  <!-- プロゲートコピーここまで -->-->
<!--</div>-->